### ISSUE TITLE
VPN settings in WebUI

### ISSUE THREAD

**Issue by Shedward** [Shedward/home-tools#3]
## Want:
- Ability to configure VPN profile for device at `/device`

## ToDo: 
- [ ] UI on `/vpn` to toggle VPN mode for any device.
  - [x] Need to implement db table for storing selected state
    - How can I identify device? By IP? By MAC?
  - [x] Need to implement toggle component
- [ ] UI on `/vpn` to add addresses to VPN lists
- [ ] #4
- [ ] Method for rendering address lists on routers

**Comment by Shedward** [comment]
- [ ] test

**Comment by Shedward** [comment]
## Implementing service for storing vpn devices

- [ ] How to automatically add vpn device on adding new device. Is it even necessary?
Possible solution could be using triggers like this:
     ```sql
    CREATE TRIGGER create_vpn_device AFTER INSERT ON devices
    BEGIN
        INSERT INTO vpn_devices VALUES(NEW.deviceid, "disabled");
    END
    ```
    ([source](https://sqlite.org/forum/info/320a27de1cfb0dfb))

**Comment by Shedward** [comment]
## Make master page

https://docs.vapor.codes/leaf/overview/#extending-templates

child.leaf
```leaf
#extend("master"):
    #export("body"):
        <p>Welcome to Vapor!</p>
    #endexport
#endextend
```

master.leaf
```leaf
<html>
    <head>
        <title>#(title)</title>
    </head>
    <body>#import("body")</body>
</html>
```

**Comment by Shedward** [comment]
# Bugs 

- [ ] `<select>` does not show properly selected value

**Comment by Shedward** [comment]
## Bugs

- [ ] `<select>` does not display selected value properly
